<head>
<!-- Bing Ads Code -->
<script>(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"5538524"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");</script><noscript><img src="//bat.bing.com/action/0?ti=5538524&Ver=2" height="0" width="0" style="display:none; visibility: hidden;" /></noscript>
<!-- End Bing Ads Code -->
<!-- FACEBOOK REMARKETING CODE -->
<!-- Place Between <head> and </head> -->

<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '365200520508834'); // Insert your pixel ID here.
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=365200520508834&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->
</head>
<%@include file="header.jsp" %>

	<section id="legal-information" class="cover main-section">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2  margin-bottom-m">
                    <h2 class="text-center margin-bottom-m">Legal Information</h2>
                   	<p>We believe the information provided on this web site to be accurate, and we make every effort to minimize errors. However, since both humans and computers are subject to mistakes, and since information and rates can change quickly, we cannot absolutely guarantee the accuracy of the information provided. If you find an error, or any inaccuracy, please let us know &mdash; we want to hear from you.</p>
            <p>Rates which may be provided by mail, e-mail, or phone or on-line are estimates and are generally reflective of the prices for the best rate classes available for various life insurance products as of the date that any rate comparisons are prepared by us. Rates provided in this manner are not firm quotes or offers, but rather estimates which are based on information provided to us by you and by the various insurance companies. Rates and availability are subject to underwriting approval by the insurance company selected, and the criteria to qualify varies widely among insurance companies. Any and all required illustrations, applications, supplemental forms, and other documents necessary to evaluate and/or apply for life insurance coverage will be provided as soon in the process as they become necessary. Policy forms vary by state. Unisex rates, which most carriers are the same as male rates, apply in Montana. <a href="policyForms.do">Click here</a> for policy forms and descriptions of available plans.</p>
            <p>Rates, plans, and availability also vary by state. Rates on most level term life insurance plans will typically increase annually after the initial guarantee period ends. Initial guarantee periods vary, and typically range from 1 to 30 years, depending upon the product you select. Suicide, misstatement, and misrepresentation restrictions may apply. Availability of premium rates and policy forms may be changed by each insurer without prior notice.</p>
            <p>If available, invitations for application for life insurance are made through Two Rivers Agency; Wheeling, Illinois, only where duly licensed and appointed. Through Two Rivers Agency or Todd Seabaugh personally, we are currently licensed in all 49 states and the District of Columbia.</p>
            <p>License numbers are available upon request and are automatically provided where required. Todd's license number is 8375446 in Missouri, 2093116 in Texas, and 692305 in Louisiana. Two Rivers Agency license number OK84978 in California and in Louisiana is 682016. No solicitation or invitation for application is currently being made in any jurisdiction in which either Todd Seabaugh (personally), d/b/a Two Rivers Agency Insurance Services is either not licensed and/or appointed with the company(s) whose rates are provided, illustrated and/or approximated by phone, mail or e-mail.</p>
            <p>If information is provided inadvertently to any person or company in a jurisdiction in which Two Rivers Agency is either not duly licensed and/or appointed, such information should be discarded (and treated as a clerical error) and you should seek a qualified, licensed, and appointed representative to assist you.</p>
            <p>We may occasionally provide premium rates, features, financial strength ratings, and/or other information about certain companies and products for which we are not appointed to sell. This information is provided as a courtesy and should not be construed as a solicitation or invitation for application for the sale of such products.</p>
            <p>For additional information regarding third-party ratings, including the scope and extent of such ratings, <a href="financialRatings.do">click here</a>.</p>
            <p>With respect to application requests, the application request form is not an application, but rather a request for an application.</p>
            <p>You agree and understand that we may contact you via phone or email to follow up regarding your request for life insurance in order to verify information for the purpose of giving you the most accurate quote possible.</p>
            <p>When you fill out our quote request form you are explicitly initiating a relationship with us (as defined by the National Do Not Call Registry), inviting and consenting to the receipt of information by Two Rivers Agency and its affiliate partners &mdash; including any call centers (which may be provided to you online, phone, email, US Mail, etc.) and, as such, are indefinitely waiving any right to claim that we or our affiliates contacted you without your express consent. At any time we will immediately honor any request to be placed on our internal "do not contact" list.</p>
            <p>Under Title V of the Gramm-Leach-Bliley Act, consumers have the right to limit the dissemination of nonpublic personal information. Two Rivers Agency maintains a strict policy against the dissemination of nonpublic personal information which may be found in the files of its clients and applicants. All Two Rivers Agency employees are trained and aware of the confidentiality of such information. Such nonpublic personal information is routinely provided by consumers to life insurance companies and related individuals including, but not limited to, their agents, wholesalers, and reinsurers, all of whom need this information in order to evaluate their inquiries, provide accurate price quotations, and underwrite their applications for coverage. As such, in order to provide the high level of service our clients have come to expect, it is understood that by filling out and submitting a quote request form, or application request form, consumers are granting Two Rivers Agency the permission to evaluate this information, and in it's sole judgment, to share it with insurance companies, their reinsurers, wholesalers, and other related parties (including the applicant) as necessary for the purpose of shopping for, evaluating, making recommendations regarding, and/or underwriting any proposed or existing life insurance coverage. Such nonpublic personal information is not used for any other purpose.</p>
            <p>Two Rivers Agency derives most of its revenue through commissions and/or fees earned from the sale of life insurance and other related products. The insurance industry is strictly regulated and extremely competitive. As such, commissions paid by insurance companies to brokers are often similar. But they can and do vary from company to company. It is entirely possible that several competing products may be available at the same, or similar, pricing and that the sale of one of them may result in a higher total commission than the sale of another. That being said, we are serious about our commitment to deliver the best value to our customers. We believe that, in order to determine which product represents the best value, we must examine the price, features, financial strength of the insurance company, as well as the availability based on your individual profile. We are also acutely aware of the fact that, as a consumer, you have many choices as to where you buy anything, including your life insurance. If we don't provide you with the best overall value, we expect that you will find someone who will. Our success as a company depends upon our continuing to deliver a superior value to our customers. We appreciate your trust, and the opportunity to earn your business.</p>
            <p>The underwriting (risk assessment) if necessary, will not begin until after the completed, hard-copy, signed application is received by the insurance company.</p>
            <p>In conjunction with any formal application for insurance, except as may be provided in a properly-executed Conditional Receipt, no coverage is in force until the insured has received the issued policy, paid the premium and completed any other policy delivery requirements that might be required by the insurance company. If there is any question, concern or ambiguity regarding this issue, please refer to the language on the insurance company's application form.</p>
            <p>Two Rivers Agency herein advises all proposed insureds NOT to cancel any existing coverage UNTIL they have received their new policy from the issuing company and found it to be satisfactory. Even if you are applying for coverage to replace an existing policy, NEVER cancel the existing coverage until the new policy is approved, in force, delivered and paid for.</p>
            <p>Free look on all policies: Two Rivers Agency provides 10 days (or longer if your state insurance laws specify) to look over any new policy and if, for any reason, you decide to cancel the policy within 10 days after receiving it, you will receive a full refund of all premiums paid, no questions asked.</p>
            <p>This web site has been painstakingly designed with the intention of providing as much information as possible, to consumers who seek to educate themselves and make informed decisions about their life insurance. However, since each individual's situation is different, none of the information provided herein should be construed as legal, tax, financial planning, or other professional advice. Only after a thorough review of your individual needs and circumstances can specific professional advice ever be appropriately provided.</p>
            <p>The information in the website is provided "as is" and without warranties of any kind either express or implied. Two Rivers Agency personally, hereby disclaim all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose.</p>
            <p>The information contained in this website is published at St. Louis Missouri for some, but not all the residents of the United States of America. The content herein should be deemed to be published by Two Rivers Agency, and not any other party, including any particular insurance company(s). In no event shall Two Rivers Agency be liable for any direct, indirect, special, incidental, or consequential damages arising out of the use of the information herein.</p>
            <p>Two Rivers Agency is not obligated to monitor any transmission made to or through any of the pages contained on this website or any website which may be linked to or from this website. However, and notwithstanding anything herein to the contrary, Two Rivers Agency has the right to monitor such transmissions and to use or disclose information gathered from this site. The name "Two Rivers Agency", the OUR LIFE COVERED<sup>SM</sup> and Two Rivers Agency logo is a federally registered trademark or service mark of RGAx d/b/a for Two Rivers Agency.</p>
            <p>All content, pages, data, and designs contained in this web site (with the exception of Insurance Company names and logos which are the exclusive property of the respective insurance companies) are copywritten by RGAx and may not be copied or reproduced, in whole or in part, in any form without our express written consent.</p>
            <p>Two Rivers Agency bears responsibility for the content of the advertisements that Two Rivers Agency creates, but not the method and manner of deliver of such advertisements. Notwithstanding anything in any other past or current agreements to the contrary, our advertising vendors represent that all means used to generate leads, including the serving/display of any advertisements, sending of mail, email, or telemarketing, are legal and do not violate the state or federal laws in the jurisdiction in which they are delivered. Our advertising vendors validate that all email is sent to 100% opt-in lists, and may be required to provide evidence of customer opt-in if a complaint arises. Our advertising vendors bear full liability for damages awarded and the reimbursement of Two Rivers Agency's legal costs as a result of any legal action brought as a result of violation of any local, state or federal laws regarding the method and manner of the delivery of the message by themselves and their affiliates Two Rivers Agency endeavors to abide by all local, state and federal laws regarding the content and delivery of electronic advertisements displayed to customers. We do this through third party providers and their affiliates and do not directly supervise or control their ultimate compliance with these policies.</p>
                </div>
            </div>
        </div>
    </section>

<%@include file="footer.jsp" %>