<%@include file="header.jsp" %>

	<section id="policy-forms" class="cover main-section">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2  margin-bottom-m">
                    <h2 class="text-center margin-bottom-m">Policy Forms</h2>
                   	 <p><strong>American General Life Companies-&nbsp;</strong>LTG - Ultra C (Form #06004) 10-year, 15-year, 20-year, 30-year is non-participating term life insurance to age 80. Coverage is renewable to age 95. Minimum issue amount is $100,000 and Maximum issue amount is $250,000. American General Life Companies, Houston, TX 77017, underwrites policy. Non-Tobacco means no nicotine use or nicotine substitutes for 5 years for preferred plus, 3 years for preferred, 2 years for standard plus and at least 12 months for standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide - In the event of the suicide of the insured, while sane or insane, within two years from the date of issue, our liability will be limited to premiums paid. Plan not available in all states. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not a statement of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>American General Life Companies: 2727-A Allen Parkway, Houston, TX 77019-2115.</p>
                    <p><strong>American General Life Companies-&nbsp;</strong>AG Select-a-Term (Form #07007) 10-, 12-, 15-, 16-, 17-, 18-, 19-, 20-, 21-, 22-, 23-, 24-, 25-, 26-, 27-, 28-, 29-, and 30-year terms. Is a non-participating term life insurance which, depending on initial age and term length, can be written to age 87 . Coverage is renewable to age 95. Minimum issue amount is $250,000. Policy is underwritten by American General Life Insurance Company, Houston, TX 77017. Non-Tobacco means no nicotine use or nicotine substitutes for 5 years for preferred plus, 3 years for preferred, 2 years for standard plus and at least 12 months for standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide, incontestability and other limits may apply. Suicide - In the event of the suicide of the insured, while sane or insane, within two years from the date of issue, our liability will be limited to premiums paid. Plan not available in all states. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not a statement of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>American General Life Companies: 2727-A Allen Parkway, Houston, TX 77019-2115.</p>
                    <p><strong>American General Life Companies-&nbsp;</strong>ROP Term (Form# 06001)-, 15-year, 20-year, 30-year is non-participating term life insurance to age 80 with a return of premium provision . Coverage is renewable to age 95. Minimum issue amount is $100,	000. Policy is underwritten by American General Life Companies, Houston, TX 77017. Non-Tobacco means no nicotine or nicotine substitutes use for 5 years for preferred plus, 3 years for preferred, 2 years for standard plus and at least 12 months for standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. All premiums with the exception of riders, flat extra and substandard premiums are refunded at the end to the term length. Suicide, incontestability and other limits may apply Suicide, incontestability and other limits may apply. Suicide - In the event of the suicide of the insured, while sane or insane, within two years from the date of issue, our liability will be limited to premiums paid. Plan not available in all states. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not a statement of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>American General Life Companies: 2727-A Allen Parkway, Houston, TX 77019-2115.</p>
                    <p><strong>American General Life Companies-&nbsp;</strong>ContinUL Extend - (Form# 05337) A flexible premium adjustable Universal Life policy that can be issued with a No Lapse feature for coverage guaranteed to age 121. Minimum issue amount is $100,000. Policy is underwritten by American General Life Companies, Houston, TX 77017. Non-Tobacco means no nicotine use or nicotine substitutes for 5 years for preferred plus, 3 years for preferred, 2 years for standard plus and at least 12 months for standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide - In the event of the suicide of the insured, while sane or insane, within two years from the date of issue, our liability will be limited to premiums paid. Plan not available in all states. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not statements of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>American General Life Companies: 2727-A Allen Parkway, Houston, TX 77019-2115.</p>
                    <p><strong>Banner Life</strong>&nbsp;- The Legal &amp; General America term life insurance premiums quoted here are based on the information provided for this quote. The quote is based on the assumption of excellent health and does not take into consideration occupational risks or other avocations. Approval and actual rates will be based upon the entire underwriting process, including but not limited to, information provided on the application, exam results and specific underwriting requirements and criteria. In most states you can return a policy without obligation within 20 days of receipt. Please refer to the policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state. Please contact the brokerage agency responsible for this website to confirm appropriate licenses for your state and contractual authorization to represent Legal &amp; General America.</p>
                    <p><strong>OPTerm</strong> - OPTerm policy form #RT-97. Not available in all states. Policy descriptions provided here are not a statement of contract and are not for public distribution. OPTerm 10 issue ages 20-80 and 20-70 in the state of Washington. OPTerm 15 issue ages 20-70 and 20-65 in the state of Washington. OPTerm 20 issue ages 20-65, 20-62 in Oregon and 20-60 in the state of Washington. OPTerm 30 issue ages 20-50. Premium rates vary by coverage amount: $100,000-$249,999, $250,000-$999,999 or $1 million and above. Premiums quoted include $50 annual policy fee. Premiums are guaranteed to stay level for 10, 15, 20 or 30 years, respectively, and increase annually after initial guarantee period. OPTerm policies can be issued in preferred plus non-tobacco, preferred non-tobacco, standard plus non-tobacco, standard non-tobacco, preferred tobacco and standard tobacco classes. OPTerm 10, 15, 20, and 30 substandard polices can be issued through Table 12, subject to underwriting discretion. Coverage can be renewed to age 95. Policies can be returned without obligation within 20 days of receipt in most states. Rates as of 02-25-2008. Two-year contestability and suicide provisions apply. Underwritten and issued by Legal &amp; General America, Frederick, MD.</p>
                    <p>Banner Life: 3275 Ennett Creek Ave., Frederick, MD 21704.</p>
                    <p><strong>Genworth Life Insurance Company</strong>&nbsp;- (Form # GE-1420)- Sure Term 10, 15, 20 and 30 is non-participating term life insurance issued to age 80/75/65/50, respectively with some age, sex, class, and state limitations. Coverage is renewable to age 98 (95 in Maryland). Minimum issue amount is $50,000. Policy is underwritten by Genworth Life Insurance Company, Richmond, VA 23230. Non-Tobacco means no nicotine use or nicotine substitutes for 5 years for preferred best, 3 years for preferred, 2 years for select and at least 12 months for standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide - If the Insured, while sane or insane dies by suicide, within two years After the Date of Issue, shown in the Schedule, the death proceeds under this Policy will be an amount equal to the premiums paid, less the loan balance as of the date of death. Plan not available in all states. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not a statement of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>Genworth Life Insurance Company: 6604 West Broad Street, Suite 400, Richmond, VA 23230.</p>
                    <p><strong>Genworth Life Insurance Company</strong>&nbsp;- Lifetime FlexPlus- (Form# ULGE02SP)- A flexible premium adjustable Universal Life policy that can be issued with a No Lapse feature for coverage guaranteed for life. Minimum issue amount is $25,000. Policy is underwritten by Genworth Life Insurance Company, Lynchburg, VA. Non-Tobacco means no nicotine use or nicotine substitutes for 5 years for preferred best, 3 years for preferred, 2 years for select and at least 12 months for standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide - If the Insured, while sane or insane dies by suicide, within two years after the Date of Issue, shown in the schedule, the death proceeds under this Policy will be an amount equal to the premiums paid, less the loan balance as of the date of death. Policy not available in all states. You can return the policy without obligation within 20 days of receipt. Policy descriptions provided here are not statements of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>Genworth Life Insurance Company: 6604 West Broad Street, Suite 400, Richmond, VA 23230.</p>
                    <p><strong>Genworth Life Insurance Company of NY-&nbsp;</strong>(Form# AM - 1420) Term 10, 15, 20 and Term 30 are non-participating term life insurance issued to age 70/65/60/50, respectively. Coverage is renewable to age 80. Minimum issue amount is $50,000. Policy is underwritten by Genworth Life Insurance Company, New York, NY 10017. Non-Tobacco means no nicotine use or nicotine substitutes for 5 years for preferred best, 3 years for preferred, 2 years for select and at least 12 months for standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide - If the Insured dies by suicide, within two years After the Date of Issue, shown in the Schedule, the death proceeds under this Policy will be an amount equal to the premiums paid as of the date of death. Plan is only available in New York. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not a statement of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>Genworth Life Insurance Company of NY: 666 Third Avenue, 9th Floor, New York, NY 10017.</p>
                    <p><strong>Genworth Life Insurance Company of NY</strong>- Lifetime FlexPlus NY- (Form# ULAML02SP (03)) - A flexible premium adjustable Universal Life policy that can be issued with a No Lapse feature for coverage guaranteed for life. Minimum issue amount is $25,000. Policy is underwritten by Genworth Life Insurance Company of New York , New York, NY. Non-Tobacco means no nicotine use or nicotine substitutes for 5 years for preferred best, 3 years for preferred, 2 years for select and at least 12 months for standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide - If the Insured, while sane or insane dies by suicide, within two years after the Date of Issue, shown in the schedule, the death proceeds under this Policy will be an amount equal to the premiums paid, less the loan balance as of the date of death. Plan is only available in New York. You can return the policy without obligation within 20 days of receipt. Policy descriptions provided here are not statements of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>Genworth Life Insurance Company of NY: 666 Third Avenue, 9th Floor, New York, NY 10017.</p>
                    <p><strong>Lincoln National Life</strong>&nbsp;- (Form #TRM5060) - Life Elements Term - 10-year, Term 15-year, Term 20-year, Term 30-year is non-participating term life insurance to age 80. Coverage is renewable to age 95. Minimum issue amount is $100,000. Policy is underwritten by Lincoln National Life Insurance Company, Fort. Wayne, IN 46801. Non-Tobacco means no nicotine use or nicotine substitutes for 5 years for preferred best and 3 years for preferred. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide - If the Insured commits while sane or insane, within two years from the Issue Date, the liability of the Company under the policy will be limited to all premiums paid. Plan not available in all states. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not a statement of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p><strong>Lincoln Life and Annuity - NY</strong>&nbsp;- Life Elements Term (Form # GTO -NY) - GTO Term 10-year, Term 15-year, Term 20-year, Term 30-year is non-participating term life insurance to age 80. Coverage is renewable to age 95. Minimum issue amount is $100,000. Policy is underwritten by Lincoln Life and Annuity Insurance Company, Syracuse, NY 13202. Non-Tobacco means no nicotine use or nicotine substitutes for 5 years for preferred best and 3 years for preferred. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide incontestability and other limits may apply. Suicide - If the Insured commits while sane or insane, within two years from the Issue Date, the liability of the Company under the policy will be limited to all premiums paid. Plan is only available in New York. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not a statement of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>Lincoln Life and Annuity of NY: 100 North Greene Street, Greensboro, NC 27401.</p>
                    <p><strong>Protective Life and Annuity - NY -</strong>&nbsp;(Form # PL11312NY) Empire Term Series, 10-year, 15-year, 20-year, 25-year, and 30-year term is a non-participating term life insurance to age 80, underwritten by Protective Life and Annuity Insurance Co., Birmingham, AL 35202. Minimum issue amount is $100,000. Non-Tobacco means no tobacco use in the last 5 years for super preferred, and 12 months for preferred and standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide - If the Insured dies by suicide, within two years from the policy date, The Company liability for the death benefit is limited to the premiums paid. Plan is only available in New York. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not a statement of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>Protective Life and Annuity: 2801 Highway 280 South, Birmingham, AL 35223.</p>
                    <p><strong>Pruco Life Insurance Company</strong>&nbsp;- (Form # IFS-A-073214) Term Essential 10, 15, 20, 30 years. A non-participating term life insurance to age 95, underwritten by Pruco Life Insurance Company, a division of Prudential Insurance Company of America, Newark, NJ 07102. Minimum issue amount is $100,000. Non-Tobacco means no tobacco use in the last 5 years for preferred best, 3 years for preferred plus, and 12 months for preferred and standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide - If the Insured whether sane or insane, dies by suicide within two years from the Issue Date, this contract will end and the Company will return the premiums paid. The contract will provide no further benefit. Plan not available in all states. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not a statement of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>Prudential Life Insurance Company: 751 Broad Street, 23rd Floor, Newark, NJ 07102.</p>
                    <p><strong>Pruco Life Insurance Company</strong>&nbsp;- PruLife ROP 15, 20, 30 years. (Form# PLTIR-2006) Is a non-participating term life insurance to age 95, with a return of premium provision. This Policy is underwritten by Pruco Life Insurance Company, a division of Prudential Insurance Company of America, Newark, NJ 07102. Minimum issue amount is $100,000. Non-Tobacco means no tobacco use in the last 5 years for preferred best, 3 years for preferred plus, and 12 months for preferred and standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide - If the Insured whether sane or insane, dies by suicide within two years from the Issue Date, this contract will end and the Company will return the premiums paid. The contract will provide no further benefit. All premiums with the exception of riders, flat extra and substandard premiums are refunded at the end to the term length. Plan not available in all states. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not statements of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>Prudential Life Insurance Company: 751 Broad Street, 23rd Floor, Newark, NJ 07102.</p>
                    <p><strong>Transamerica Life Insurance Company -&nbsp;</strong>Trendsetter® Super Series are term life insurance policies issued by Transamerica Life Insurance Company, Cedar Rapids, IA and in New York by Transamerica Financial Life Insurance Company, Harrison, NY. Policy Forms ICC16 TL22, TL22, 1-322 11-107, 1-306 11-107, 1-305 11-107, 1-304 11-107, 1-303 11-107, or 1-334 11-107 issued by Transamerica Life Insurance Company and 3-306 38-111, 3-305 38-111, 3-304 38-111, 3-303 38-111, or 3-334 38-111 issued by Transamerica Financial Life Insurance Company. Premiums increase annually for Trendsetter Super YRT, and beginning in year 11 for the 10- year policy, in year 16 for the 15-year policy, in year 21 for the 20-year policy, in year 26 for the 25-year policy, and in year 31 for the 30-year policy. Policy forms and numbers may vary, and these policies and the riders may not be available in all jurisdictions. Insurance eligibility and premiums are subject to underwriting. In most states, in the event of suicide during the first two policy years, death benefits are limited only to the return of premiums paid.</p>
                    <p>Transamerica Financial Life Insurance Company is authorized to conduct business in New York. Transamerica Life Insurance Company is authorized to conduct business in all other states. State variations may apply.</p>
                    <p>As a highly fit person, you may qualify for preferred plus class coverage. However, this is non-binding prior to your application.</p>
                    <p>No quotes are final until underwriting is completed.  Other underwriting classes, face amounts and payment modes are available.  Premiums will be lower if paid annually.  Rates subject to change without notice.</p>
                    <p>The recommended coverage amount is determined by Two River Agency. Two River Agency is an independent contractor representing Transamerica Life Insurance Company and Transamerica Financial Life Insurance Company.</p>
                    <p><strong>United States Life Insurance Company</strong>&nbsp;<strong>-&nbsp;</strong>Select-a-Term (Form #07007)-10-, 12-, 15-, 16-, 17-, 18-, 19-, 20-, 21-, 22-, 23-, 24-, 25-, 26-, 27-, 28-, 29-, and 30-year terms. Is a non-participating term life insurance to age 80. Coverage is renewable to age 95. Minimum issue amount is $250,000. Policy is underwritten by United Sates Life Insurance Company, New York, NY 10022. Non-Tobacco means no nicotine use or nicotine substitutes for 5 years for preferred plus, 3 years for preferred, 2 years for standard plus and at least 12 months for standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide, incontestability and other limits may apply. Suicide - In the event of the suicide of the insured, within two years from the date of issue, the Company liability will be limited to the premiums paid. Plan is only available in New York. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not a statement of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>United States Life Insurance Company: 3600 Route 66, PO Box 1580, Neptune, NJ 07754-1580.</p>
                    <p><strong>United States Life Insurance Company&nbsp;</strong>- ContinUL Extend - (Form# 05337N) A flexible premium adjustable Universal Life policy that can be issued with a No Lapse feature for coverage guaranteed to age 121. Minimum issue amount is $100,000. Policy is underwritten by the United States Life Insurance Company in the city of New York, NY 10022. Non-Tobacco means no nicotine use or nicotine substitutes for 5 years for preferred plus, 3 years for preferred, 2 years for standard plus and at least 12 months for standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide - In the event of the suicide of the insured, while sane or insane, within two years from the date of issue, our liability will be limited to premiums paid. Plan only available in New York. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not statements of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>United States Life Insurance Company: 3600 Route 66, PO Box 1580, Neptune, NJ 07754-1580.</p>
                    <p><strong>West Coast Life</strong>&nbsp;- (Form#05113700) Focus Term Series- 10-year, 15-year, 20-year, 25-year, and 30-year term, is a non-participating term life insurance to age 95, underwritten by West Coast Life Insurance Company, San Francisco, CA 94119. Minimum issue amount is $100,000. Non-Tobacco means no tobacco use in the last 5 years for super preferred, and 12 months for preferred and standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide - If the Insured dies from suicide, whether sane or insane, within (2) two years from the Policy Date. The Company is only liable for the return of any premium(s) received. The contract will provide no further benefit. Plan not available in all states. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not a statement of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>West Coast Life Insurance Company: 2801 Highway 280 South, Birmingham, AL 35223.</p>
                    <p><strong>West Coast Life</strong>&nbsp;- LifeTime Platinum II - (Form# WC-U15 11-06) A flexible premium adjustable Universal Life policy that can be issued with a No Lapse feature for coverage guaranteed to age 121. Minimum Issue amount is $100,000. Underwritten by West Coast Life Insurance Company, San Francisco, CA 94119. Non-Tobacco means no tobacco use in the last 5 years for super preferred, and 12 months for preferred and standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide - If the Insured dies from suicide, whether sane or insane, within (2) two years from the Policy Date. The Company is only liable for the return of any premium(s) received. The contract will provide no further benefit. Plan not available in all states. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not statements of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>West Coast Life Insurance Company: 2801 Highway 280 South, Birmingham, AL 35223.</p>
                    <p><strong>William Penn</strong>&nbsp;- The William Penn life insurance premiums quoted here are based on the information provided for this quote. The quote is based on the assumption of excellent health and does not take into consideration occupational risks or other avocations. Approval and actual rates will be based upon the entire underwriting process, including but not limited to, information provided on the application, exam results and specific underwriting requirements and criteria. You can return a policy without obligation within 20 day of receipt. Policy descriptions provided here are not a statement of contract. Please refer to the policy form for full disclosure of benefits and limitations. Please contact the brokerage agency responsible for this website to confirm appropriate licenses for your state and contractual authorization to represent William Penn.</p>
                    <p>Penn Term Series policy form #T-RC-IP/97. Available only in New York. Policy descriptions provided here are not a statement of contract and are not for public distribution. Penn Term 10 issue ages 20-80. Penn Term 15 issue ages 20-70. Penn Term 20 issue ages 20-65. Penn Term 30 issue ages 20-50. Premium rates vary by coverage amount: $100,000-$249,999, $250,000-$999,999 and $1 million and above. Premiums quoted include $50 annual policy fee. Initial premiums remain level for 10, 15, 20 and 30 years respectively. After the initial level term period, premiums increase annually to age 95. Penn Term 10, 15, 20 and 30 can be issued in preferred plus non-tobacco, preferred non-tobacco, standard plus non-tobacco, or standard non-tobacco, preferred tobacco and standard tobacco rates. Substandard policies can be issued through Table 12, subject to underwriting discretion. Policies can be returned without obligation within 20 days of receipt. Rates as of 4-10-2008. Two-year contestability and suicide provisions apply. Underwritten and issued by William Penn Life Insurance Company of New York, Garden City, NY.</p>
                    <p>William Penn: 100 Quentin Roosevelt Boulevard, Garden City, NY 11530.</p>
                    <p><strong>Liberty Life</strong>- (Form # LT (06-04) - Level Term 10-year, 15-year, 20-year, and 30-year term is a non-participating term life insurance to age 95, underwritten by Liberty Life Insurance Company, Greenville, SC 29602. Minimum issue amount is $100,000. Non-Tobacco means no tobacco use in the last 12 months for preferred plus, preferred and standard. The most favorable rate classes (and lowest rates) are generally intended for those who can meet strict health/lifestyle criteria. All rates are subject to underwriting qualifications, exam results and personal physician statements. Suicide, incontestability and other limits may apply. Suicide - Suicide, while sane or insane, within two years from the Date of Issue, is a risk not covered. In such event, the Company liability is limited to the refund of all premiums paid for the Policy. Plan not available in all states. You can return the policy without obligation within 10 days of receipt. Policy descriptions provided here are not a statement of contract. Please refer to policy form for full disclosure of benefits and limitations. Forms and policy provisions may vary by state.</p>
                    <p>Liberty Life: PO Box 1389, Greenville, SC 29602-1389.</p>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div id="ta-code">
                        <small>OLC115117</small>
                    </div>
                </div>
            </div>
        </div>
    </section>

<%@include file="footer.jsp" %>